///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyFirstTestProject.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Amazon_Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("54894421-98c9-40c2-8bbd-3eaa77816017")]
    public partial class Amazon_Repo : RepoGenBaseFolder
    {
        static Amazon_Repo instance = new Amazon_Repo();

        /// <summary>
        /// Gets the singleton class instance representing the Amazon_Repo element repository.
        /// </summary>
        [RepositoryFolder("54894421-98c9-40c2-8bbd-3eaa77816017")]
        public static Amazon_Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Amazon_Repo() 
            : base("Amazon_Repo", "/", null, 0, false, "54894421-98c9-40c2-8bbd-3eaa77816017", ".\\RepositoryImages\\Amazon_Repo54894421.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("54894421-98c9-40c2-8bbd-3eaa77816017")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class Amazon_RepoFolders
    {
    }
#pragma warning restore 0436
}