///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyFirstTestProject.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GitHubRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("ef16ba2d-9dcf-499c-9cf8-70a5eb93ce42")]
    public partial class GitHubRepo : RepoGenBaseFolder
    {
        static GitHubRepo instance = new GitHubRepo();
        GitHubRepoFolders.TheWorldsLeadingSoftwareDevelopmentAppFolder _theworldsleadingsoftwaredevelopment;

        /// <summary>
        /// Gets the singleton class instance representing the GitHubRepo element repository.
        /// </summary>
        [RepositoryFolder("ef16ba2d-9dcf-499c-9cf8-70a5eb93ce42")]
        public static GitHubRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GitHubRepo() 
            : base("GitHubRepo", "/", null, 0, false, "ef16ba2d-9dcf-499c-9cf8-70a5eb93ce42", ".\\RepositoryImages\\GitHubRepoef16ba2d.rximgres")
        {
            _theworldsleadingsoftwaredevelopment = new GitHubRepoFolders.TheWorldsLeadingSoftwareDevelopmentAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ef16ba2d-9dcf-499c-9cf8-70a5eb93ce42")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The TheWorldsLeadingSoftwareDevelopment folder.
        /// </summary>
        [RepositoryFolder("c0a89691-105f-4d05-b635-d446fa4004a1")]
        public virtual GitHubRepoFolders.TheWorldsLeadingSoftwareDevelopmentAppFolder TheWorldsLeadingSoftwareDevelopment
        {
            get { return _theworldsleadingsoftwaredevelopment; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class GitHubRepoFolders
    {
        /// <summary>
        /// The TheWorldsLeadingSoftwareDevelopmentAppFolder folder.
        /// </summary>
        [RepositoryFolder("c0a89691-105f-4d05-b635-d446fa4004a1")]
        public partial class TheWorldsLeadingSoftwareDevelopmentAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _link_signinInfo;
            RepoItemInfo _txt_usernameInfo;
            RepoItemInfo _txt_passwordInfo;
            RepoItemInfo _btn_signinInfo;

            /// <summary>
            /// Creates a new TheWorldsLeadingSoftwareDevelopment  folder.
            /// </summary>
            public TheWorldsLeadingSoftwareDevelopmentAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TheWorldsLeadingSoftwareDevelopment", "/dom[@domain='github.com']", parentFolder, 30000, null, false, "c0a89691-105f-4d05-b635-d446fa4004a1", "")
            {
                _link_signinInfo = new RepoItemInfo(this, "link_SignIn", "body/div[1]/header/div/div[2]/div[2]/a[@innertext='Sign in']", 30000, null, "8b93be1e-dbd0-4640-a278-526d8914e4e3");
                _txt_usernameInfo = new RepoItemInfo(this, "txt_UserName", ".//input[#'login_field']", 30000, null, "9558f6cd-9239-4167-9e72-2944f201baa0");
                _txt_passwordInfo = new RepoItemInfo(this, "txt_Password", ".//input[#'password']", 30000, null, "0cf622af-bb48-4838-bcc4-07b9ea929cf3");
                _btn_signinInfo = new RepoItemInfo(this, "btn_SignIn", ".//div[#'login']/form[@action='https://github.com/session']/?/?/input[@name='commit']", 30000, null, "31f08f6c-99a8-4c5d-ac96-eb1cd6b485b4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c0a89691-105f-4d05-b635-d446fa4004a1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c0a89691-105f-4d05-b635-d446fa4004a1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The link_SignIn item.
            /// </summary>
            [RepositoryItem("8b93be1e-dbd0-4640-a278-526d8914e4e3")]
            public virtual Ranorex.ATag link_SignIn
            {
                get
                {
                    return _link_signinInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The link_SignIn item info.
            /// </summary>
            [RepositoryItemInfo("8b93be1e-dbd0-4640-a278-526d8914e4e3")]
            public virtual RepoItemInfo link_SignInInfo
            {
                get
                {
                    return _link_signinInfo;
                }
            }

            /// <summary>
            /// The txt_UserName item.
            /// </summary>
            [RepositoryItem("9558f6cd-9239-4167-9e72-2944f201baa0")]
            public virtual Ranorex.InputTag txt_UserName
            {
                get
                {
                    return _txt_usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_UserName item info.
            /// </summary>
            [RepositoryItemInfo("9558f6cd-9239-4167-9e72-2944f201baa0")]
            public virtual RepoItemInfo txt_UserNameInfo
            {
                get
                {
                    return _txt_usernameInfo;
                }
            }

            /// <summary>
            /// The txt_Password item.
            /// </summary>
            [RepositoryItem("0cf622af-bb48-4838-bcc4-07b9ea929cf3")]
            public virtual Ranorex.InputTag txt_Password
            {
                get
                {
                    return _txt_passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_Password item info.
            /// </summary>
            [RepositoryItemInfo("0cf622af-bb48-4838-bcc4-07b9ea929cf3")]
            public virtual RepoItemInfo txt_PasswordInfo
            {
                get
                {
                    return _txt_passwordInfo;
                }
            }

            /// <summary>
            /// The btn_SignIn item.
            /// </summary>
            [RepositoryItem("31f08f6c-99a8-4c5d-ac96-eb1cd6b485b4")]
            public virtual Ranorex.InputTag btn_SignIn
            {
                get
                {
                    return _btn_signinInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The btn_SignIn item info.
            /// </summary>
            [RepositoryItemInfo("31f08f6c-99a8-4c5d-ac96-eb1cd6b485b4")]
            public virtual RepoItemInfo btn_SignInInfo
            {
                get
                {
                    return _btn_signinInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}