///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyFirstTestProject.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JenKinsRepoItem element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("68081677-099e-48cb-b9ce-85a468908c6f")]
    public partial class JenKinsRepoItem : RepoGenBaseFolder
    {
        static JenKinsRepoItem instance = new JenKinsRepoItem();
        JenKinsRepoItemFolders.JenkinsAppFolder _jenkins;
        JenKinsRepoItemFolders.RestorePagesAppFolder _restorepages;

        /// <summary>
        /// Gets the singleton class instance representing the JenKinsRepoItem element repository.
        /// </summary>
        [RepositoryFolder("68081677-099e-48cb-b9ce-85a468908c6f")]
        public static JenKinsRepoItem Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JenKinsRepoItem() 
            : base("JenKinsRepoItem", "/", null, 0, false, "68081677-099e-48cb-b9ce-85a468908c6f", ".\\RepositoryImages\\JenKinsRepoItem68081677.rximgres")
        {
            _jenkins = new JenKinsRepoItemFolders.JenkinsAppFolder(this);
            _restorepages = new JenKinsRepoItemFolders.RestorePagesAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("68081677-099e-48cb-b9ce-85a468908c6f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Jenkins folder.
        /// </summary>
        [RepositoryFolder("965993e0-419e-4ebc-a66f-99428c899001")]
        public virtual JenKinsRepoItemFolders.JenkinsAppFolder Jenkins
        {
            get { return _jenkins; }
        }

        /// <summary>
        /// The RestorePages folder.
        /// </summary>
        [RepositoryFolder("c7dd46bb-33fa-489b-9b7a-c4abe4f209e2")]
        public virtual JenKinsRepoItemFolders.RestorePagesAppFolder RestorePages
        {
            get { return _restorepages; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class JenKinsRepoItemFolders
    {
        /// <summary>
        /// The JenkinsAppFolder folder.
        /// </summary>
        [RepositoryFolder("965993e0-419e-4ebc-a66f-99428c899001")]
        public partial class JenkinsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txt_jusernameInfo;
            RepoItemInfo _txt_jpasswordInfo;
            RepoItemInfo _btn_loginInfo;
            RepoItemInfo _link_loginInfo;
            RepoItemInfo _link_logoutInfo;

            /// <summary>
            /// Creates a new Jenkins  folder.
            /// </summary>
            public JenkinsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Jenkins", "/dom[@domain='localhost:8080']", parentFolder, 30000, null, false, "965993e0-419e-4ebc-a66f-99428c899001", "")
            {
                _txt_jusernameInfo = new RepoItemInfo(this, "txt_JUsername", ".//input[#'j_username']", 30000, null, "9804359b-5b0c-4a7d-a3b4-bb412e21ed2b");
                _txt_jpasswordInfo = new RepoItemInfo(this, "txt_JPassword", ".//div[#'main-panel']/?/?/form[@name='login']/table//input[@name='j_password']", 30000, null, "496905a4-b380-4134-b696-43238fd440c8");
                _btn_loginInfo = new RepoItemInfo(this, "btn_LogIn", ".//div[#'main-panel']/?/?/form[@name='login']//button[@innertext='log in']", 30000, null, "f4d4efe0-fbe9-479a-9e0b-431505d40e5b");
                _link_loginInfo = new RepoItemInfo(this, "link_LogIn", ".//div[#'header']//b[@innertext='log in']", 30000, null, "8844ba75-7a4b-46b2-b107-500b241563ec");
                _link_logoutInfo = new RepoItemInfo(this, "link_LogOut", ".//div[#'header']/?/?/span[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\|\\ \\ ']/?/?/b[@innertext='log out']", 30000, null, "ef06be2c-b393-42e0-ad0f-d06470e6dec6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("965993e0-419e-4ebc-a66f-99428c899001")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("965993e0-419e-4ebc-a66f-99428c899001")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txt_JUsername item.
            /// </summary>
            [RepositoryItem("9804359b-5b0c-4a7d-a3b4-bb412e21ed2b")]
            public virtual Ranorex.InputTag txt_JUsername
            {
                get
                {
                    return _txt_jusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_JUsername item info.
            /// </summary>
            [RepositoryItemInfo("9804359b-5b0c-4a7d-a3b4-bb412e21ed2b")]
            public virtual RepoItemInfo txt_JUsernameInfo
            {
                get
                {
                    return _txt_jusernameInfo;
                }
            }

            /// <summary>
            /// The txt_JPassword item.
            /// </summary>
            [RepositoryItem("496905a4-b380-4134-b696-43238fd440c8")]
            public virtual Ranorex.InputTag txt_JPassword
            {
                get
                {
                    return _txt_jpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_JPassword item info.
            /// </summary>
            [RepositoryItemInfo("496905a4-b380-4134-b696-43238fd440c8")]
            public virtual RepoItemInfo txt_JPasswordInfo
            {
                get
                {
                    return _txt_jpasswordInfo;
                }
            }

            /// <summary>
            /// The btn_LogIn item.
            /// </summary>
            [RepositoryItem("f4d4efe0-fbe9-479a-9e0b-431505d40e5b")]
            public virtual Ranorex.ButtonTag btn_LogIn
            {
                get
                {
                    return _btn_loginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The btn_LogIn item info.
            /// </summary>
            [RepositoryItemInfo("f4d4efe0-fbe9-479a-9e0b-431505d40e5b")]
            public virtual RepoItemInfo btn_LogInInfo
            {
                get
                {
                    return _btn_loginInfo;
                }
            }

            /// <summary>
            /// The link_LogIn item.
            /// </summary>
            [RepositoryItem("8844ba75-7a4b-46b2-b107-500b241563ec")]
            public virtual Ranorex.BTag link_LogIn
            {
                get
                {
                    return _link_loginInfo.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The link_LogIn item info.
            /// </summary>
            [RepositoryItemInfo("8844ba75-7a4b-46b2-b107-500b241563ec")]
            public virtual RepoItemInfo link_LogInInfo
            {
                get
                {
                    return _link_loginInfo;
                }
            }

            /// <summary>
            /// The link_LogOut item.
            /// </summary>
            [RepositoryItem("ef06be2c-b393-42e0-ad0f-d06470e6dec6")]
            public virtual Ranorex.BTag link_LogOut
            {
                get
                {
                    return _link_logoutInfo.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The link_LogOut item info.
            /// </summary>
            [RepositoryItemInfo("ef06be2c-b393-42e0-ad0f-d06470e6dec6")]
            public virtual RepoItemInfo link_LogOutInfo
            {
                get
                {
                    return _link_logoutInfo;
                }
            }
        }

        /// <summary>
        /// The RestorePagesAppFolder folder.
        /// </summary>
        [RepositoryFolder("c7dd46bb-33fa-489b-9b7a-c4abe4f209e2")]
        public partial class RestorePagesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn_closeInfo;

            /// <summary>
            /// Creates a new RestorePages  folder.
            /// </summary>
            public RestorePagesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RestorePages", "/form[@title='Restore pages?']", parentFolder, 30000, null, true, "c7dd46bb-33fa-489b-9b7a-c4abe4f209e2", "")
            {
                _btn_closeInfo = new RepoItemInfo(this, "btn_Close", "element[@accessiblename='Restore pages?']//button[@accessiblename='Close']", 30000, null, "0429ddaf-5d23-4183-bc2c-570c4192f0b7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c7dd46bb-33fa-489b-9b7a-c4abe4f209e2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c7dd46bb-33fa-489b-9b7a-c4abe4f209e2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btn_Close item.
            /// </summary>
            [RepositoryItem("0429ddaf-5d23-4183-bc2c-570c4192f0b7")]
            public virtual Ranorex.Button btn_Close
            {
                get
                {
                    return _btn_closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_Close item info.
            /// </summary>
            [RepositoryItemInfo("0429ddaf-5d23-4183-bc2c-570c4192f0b7")]
            public virtual RepoItemInfo btn_CloseInfo
            {
                get
                {
                    return _btn_closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}