///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyFirstTestProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The KeyPassLoginModule recording.
    /// </summary>
    [TestModule("bfd232ec-6106-491e-8577-07a093ed659b", ModuleType.Recording, 1)]
    public partial class KeyPassLoginModule : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyFirstTestProjectRepository repository.
        /// </summary>
        public static MyFirstTestProjectRepository repo = MyFirstTestProjectRepository.Instance;

        static KeyPassLoginModule instance = new KeyPassLoginModule();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public KeyPassLoginModule()
        {
            ExicutablePath_START_SUT = "C:\\Program Files (x86)\\Ranorex 8.2\\Samples\\Desktop\\KeePass Sample\\KeePassTestSuite\\KeePass\\KeePass.exe";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static KeyPassLoginModule Instance
        {
            get { return instance; }
        }

#region Variables

        string _ExicutablePath_START_SUT;

        /// <summary>
        /// Gets or sets the value of variable ExicutablePath_START_SUT.
        /// </summary>
        [TestVariable("aaa86f74-75b6-4597-a791-4320a551f25b")]
        public string ExicutablePath_START_SUT
        {
            get { return _ExicutablePath_START_SUT; }
            set { _ExicutablePath_START_SUT = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginPage.Text' at 19;11.", repo.LoginPage.TextInfo, new RecordItemIndex(0));
            repo.LoginPage.Text.Click("19;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'rx' with focus on 'LoginPage.Text'.", repo.LoginPage.TextInfo, new RecordItemIndex(1));
            repo.LoginPage.Text.PressKeys("rx");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginPage.MBtnOK' at 43;12.", repo.LoginPage.MBtnOKInfo, new RecordItemIndex(2));
            repo.LoginPage.MBtnOK.Click("43;12");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
