///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyFirstTestProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The KeyPassValidateEntry recording.
    /// </summary>
    [TestModule("41817111-b91f-4138-9837-15d65769003d", ModuleType.Recording, 1)]
    public partial class KeyPassValidateEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyFirstTestProjectRepository repository.
        /// </summary>
        public static MyFirstTestProjectRepository repo = MyFirstTestProjectRepository.Instance;

        static KeyPassValidateEntry instance = new KeyPassValidateEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public KeyPassValidateEntry()
        {
            ValidateTitle = "KeyPassDemo";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static KeyPassValidateEntry Instance
        {
            get { return instance; }
        }

#region Variables

        string _ValidateTitle;

        /// <summary>
        /// Gets or sets the value of variable ValidateTitle.
        /// </summary>
        [TestVariable("fa2e4c38-6357-4aac-b9d1-112ed0421cb2")]
        public string ValidateTitle
        {
            get { return _ValidateTitle; }
            set { _ValidateTitle = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$ValidateTitle) on item 'MainForm.KeyPassDemo'.", repo.MainForm.KeyPassDemoInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.MainForm.KeyPassDemoInfo, "Text", ValidateTitle);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
