///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyFirstTestProject
{
    public partial class KeyPassCloseApplication
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }


        public void MergedUserCodeMethod(RepoItemInfo buttonInfo, RepoItemInfo buttonInfo1)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at 29;23.", buttonInfo);
            buttonInfo.FindAdapter<Button>().Click("29;23");
            var buttonDiscardChanges = repo.KeePass1.ButtonDiscardChanges;
            if (buttonDiscardChanges.Visible) {
            	buttonDiscardChanges.Click();
            	
            }
        }

    }
}
