///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyFirstTestProject
{
    public partial class KeyPassAddNewEntry
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_MBtnOK1(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at 22;17.", buttonInfo);
            buttonInfo.FindAdapter<Button>().Click("22;17");
        }

        public void Mouse_Click_MenuItem1Year(RepoItemInfo menuitemInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'menuitemInfo' at 35;1.", menuitemInfo);
            menuitemInfo.FindAdapter<MenuItem>().Click("35;1");
        }

        public void Mouse_DoubleClick_MBtnStandardExpires(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'buttonInfo' at 19;15.", buttonInfo);
            buttonInfo.FindAdapter<Button>().DoubleClick("19;15");
        }

        public void Key_sequence()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'http://bitly.com/wp demo'.");
            Keyboard.Press("http://bitly.com/wp demo");
        }

        public void Mouse_Click_URL(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'textInfo' at 15;7.", textInfo);
            textInfo.FindAdapter<Text>().Click("15;7");
        }

        public void Key_sequence_Repeat(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Demo123' with focus on 'textInfo'.", textInfo);
            textInfo.FindAdapter<Text>().PressKeys("Demo123");
        }

        public void Mouse_Click_Repeat(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'textInfo' at Center.", textInfo);
            textInfo.FindAdapter<Text>().Click();
        }

        public void Key_sequence_Password(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Demo123' with focus on 'textInfo'.", textInfo);
            textInfo.FindAdapter<Text>().PressKeys("Demo123");
        }

        public void Mouse_Click_Password(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'textInfo' at 158;7.", textInfo);
            textInfo.FindAdapter<Text>().Click("158;7");
        }

        public void Key_sequence_UserName(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'KeyPassDemo' with focus on 'textInfo'.", textInfo);
            textInfo.FindAdapter<Text>().PressKeys("KeyPassDemo");
        }

        public void Mouse_Click_UserName(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'textInfo' at 28;7.", textInfo);
            textInfo.FindAdapter<Text>().Click("28;7");
        }

        public void Mouse_Click_MBtnOK(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at 26;7.", buttonInfo);
            buttonInfo.FindAdapter<Button>().Click("26;7");
        }

        public void Mouse_Click_ListItem1(RepoItemInfo listitemInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'listitemInfo' at 6;4.", listitemInfo);
            listitemInfo.FindAdapter<ListItem>().Click("6;4");
        }

        public void Mouse_Click_MBtnIcon(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at 13;9.", buttonInfo);
            buttonInfo.FindAdapter<Button>().Click("13;9");
        }

        public void Key_sequence_Text(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'KeyPassDemo' with focus on 'textInfo'.", textInfo);
            textInfo.FindAdapter<Text>().PressKeys("KeyPassDemo");
        }

        public void Mouse_Click_Text(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'textInfo' at 34;9.", textInfo);
            textInfo.FindAdapter<Text>().Click("34;9");
        }

        public void Mouse_Click_AddEntry(RepoItemInfo menuitemInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'menuitemInfo' at 36;6.", menuitemInfo);
            menuitemInfo.FindAdapter<MenuItem>().Click("36;6");
        }

        public void Mouse_Click_Edit(RepoItemInfo menuitemInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'menuitemInfo' at 30;7.", menuitemInfo);
            menuitemInfo.FindAdapter<MenuItem>().Click("30;7");
        }

        public void Key_sequence_Password1(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Demo123' with focus on 'textInfo'.", textInfo);
            textInfo.FindAdapter<Text>().PressKeys("Demo123");
        }

    }
}
