///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyFirstTestProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The KeyPassDeleteEntry recording.
    /// </summary>
    [TestModule("d6e1348a-f536-460c-b274-30802d62e900", ModuleType.Recording, 1)]
    public partial class KeyPassDeleteEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyFirstTestProjectRepository repository.
        /// </summary>
        public static MyFirstTestProjectRepository repo = MyFirstTestProjectRepository.Instance;

        static KeyPassDeleteEntry instance = new KeyPassDeleteEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public KeyPassDeleteEntry()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static KeyPassDeleteEntry Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'MainForm.KeyPassDemo' at 50;5.", repo.MainForm.KeyPassDemoInfo, new RecordItemIndex(0));
            repo.MainForm.KeyPassDemo.Click(System.Windows.Forms.MouseButtons.Right, "50;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.DeleteEntry' at 61;2.", repo.KeePass.DeleteEntryInfo, new RecordItemIndex(1));
            repo.KeePass.DeleteEntry.Click("61;2");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
