///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyFirstTestProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The KeyPassVersionValidate recording.
    /// </summary>
    [TestModule("68a09609-7801-4059-a916-cdf62082487b", ModuleType.Recording, 1)]
    public partial class KeyPassVersionValidate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyFirstTestProjectRepository repository.
        /// </summary>
        public static MyFirstTestProjectRepository repo = MyFirstTestProjectRepository.Instance;

        static KeyPassVersionValidate instance = new KeyPassVersionValidate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public KeyPassVersionValidate()
        {
            varKeyPassVersion = "2.20.1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static KeyPassVersionValidate Instance
        {
            get { return instance; }
        }

#region Variables

        string _varKeyPassVersion;

        /// <summary>
        /// Gets or sets the value of variable varKeyPassVersion.
        /// </summary>
        [TestVariable("5385c40c-5e18-429f-a690-f78a81a3109f")]
        public string varKeyPassVersion
        {
            get { return _varKeyPassVersion; }
            set { _varKeyPassVersion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Help' at 29;8.", repo.MainForm.HelpInfo, new RecordItemIndex(0));
            repo.MainForm.Help.Click("29;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.AboutKeePass' at 49;5.", repo.KeePass.AboutKeePassInfo, new RecordItemIndex(1));
            repo.KeePass.AboutKeePass.Click("49;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varKeyPassVersion) on item 'AboutForm.Cell2201'.", repo.AboutForm.Cell2201Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.AboutForm.Cell2201Info, "Text", varKeyPassVersion);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AboutForm.MBtnOK' at 55;14.", repo.AboutForm.MBtnOKInfo, new RecordItemIndex(3));
            repo.AboutForm.MBtnOK.Click("55;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Close' at 14;13.", repo.MainForm.CloseInfo, new RecordItemIndex(4));
            repo.MainForm.Close.Click("14;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass1.ButtonDiscardChanges' at 133;25.", repo.KeePass1.ButtonDiscardChangesInfo, new RecordItemIndex(5));
            repo.KeePass1.ButtonDiscardChanges.Click("133;25");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
