///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyFirstTestProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyFirstTestProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("f7bc0049-88e2-4852-88d2-fcf38eb3b04b")]
    public partial class MyFirstTestProjectRepository : RepoGenBaseFolder
    {
        static MyFirstTestProjectRepository instance = new MyFirstTestProjectRepository();
        MyFirstTestProjectRepositoryFolders.LoginPageAppFolder _loginpage;
        MyFirstTestProjectRepositoryFolders.MainFormAppFolder _mainform;
        MyFirstTestProjectRepositoryFolders.KeePassAppFolder _keepass;
        MyFirstTestProjectRepositoryFolders.PwEntryFormAppFolder _pwentryform;
        MyFirstTestProjectRepositoryFolders.IconPickerFormAppFolder _iconpickerform;
        MyFirstTestProjectRepositoryFolders.KeePass1AppFolder _keepass1;
        MyFirstTestProjectRepositoryFolders.AboutFormAppFolder _aboutform;

        /// <summary>
        /// Gets the singleton class instance representing the MyFirstTestProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("f7bc0049-88e2-4852-88d2-fcf38eb3b04b")]
        public static MyFirstTestProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyFirstTestProjectRepository() 
            : base("MyFirstTestProjectRepository", "/", null, 0, false, "f7bc0049-88e2-4852-88d2-fcf38eb3b04b", ".\\RepositoryImages\\MyFirstTestProjectRepositoryf7bc0049.rximgres")
        {
            _loginpage = new MyFirstTestProjectRepositoryFolders.LoginPageAppFolder(this);
            _mainform = new MyFirstTestProjectRepositoryFolders.MainFormAppFolder(this);
            _keepass = new MyFirstTestProjectRepositoryFolders.KeePassAppFolder(this);
            _pwentryform = new MyFirstTestProjectRepositoryFolders.PwEntryFormAppFolder(this);
            _iconpickerform = new MyFirstTestProjectRepositoryFolders.IconPickerFormAppFolder(this);
            _keepass1 = new MyFirstTestProjectRepositoryFolders.KeePass1AppFolder(this);
            _aboutform = new MyFirstTestProjectRepositoryFolders.AboutFormAppFolder(this);
        }

#region Variables

        string _varExpires = "1 Year";

        /// <summary>
        /// Gets or sets the value of variable varExpires.
        /// </summary>
        [TestVariable("c57b4175-cd8f-4f08-999d-4a396515ce22")]
        public string varExpires
        {
            get { return _varExpires; }
            set { _varExpires = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f7bc0049-88e2-4852-88d2-fcf38eb3b04b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LoginPage folder.
        /// </summary>
        [RepositoryFolder("85ca4e89-8c5b-4025-9966-63a3db391f98")]
        public virtual MyFirstTestProjectRepositoryFolders.LoginPageAppFolder LoginPage
        {
            get { return _loginpage; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("309dcc16-8068-4155-8c07-d984e5f6d2c1")]
        public virtual MyFirstTestProjectRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The KeePass folder.
        /// </summary>
        [RepositoryFolder("d2020d88-b02c-4afc-99bf-30a84cdcf093")]
        public virtual MyFirstTestProjectRepositoryFolders.KeePassAppFolder KeePass
        {
            get { return _keepass; }
        }

        /// <summary>
        /// The PwEntryForm folder.
        /// </summary>
        [RepositoryFolder("5044a4b7-ab54-4001-872e-7455f204cbca")]
        public virtual MyFirstTestProjectRepositoryFolders.PwEntryFormAppFolder PwEntryForm
        {
            get { return _pwentryform; }
        }

        /// <summary>
        /// The IconPickerForm folder.
        /// </summary>
        [RepositoryFolder("e377384c-8354-487b-bc18-b529a5181c52")]
        public virtual MyFirstTestProjectRepositoryFolders.IconPickerFormAppFolder IconPickerForm
        {
            get { return _iconpickerform; }
        }

        /// <summary>
        /// The KeePass1 folder.
        /// </summary>
        [RepositoryFolder("eea33797-6951-4fbb-b21e-a86359bb687d")]
        public virtual MyFirstTestProjectRepositoryFolders.KeePass1AppFolder KeePass1
        {
            get { return _keepass1; }
        }

        /// <summary>
        /// The AboutForm folder.
        /// </summary>
        [RepositoryFolder("e46e2838-cbaa-4645-93f7-8581db15098c")]
        public virtual MyFirstTestProjectRepositoryFolders.AboutFormAppFolder AboutForm
        {
            get { return _aboutform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class MyFirstTestProjectRepositoryFolders
    {
        /// <summary>
        /// The LoginPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("85ca4e89-8c5b-4025-9966-63a3db391f98")]
        public partial class LoginPageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, true, "85ca4e89-8c5b-4025-9966-63a3db391f98", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", 30000, null, "93235cea-fc03-4f17-ab9e-e68a0fc05916");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "98625ce7-fc63-405a-917c-0ec3aa539773");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("85ca4e89-8c5b-4025-9966-63a3db391f98")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("85ca4e89-8c5b-4025-9966-63a3db391f98")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("93235cea-fc03-4f17-ab9e-e68a0fc05916")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("93235cea-fc03-4f17-ab9e-e68a0fc05916")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("98625ce7-fc63-405a-917c-0ec3aa539773")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("98625ce7-fc63-405a-917c-0ec3aa539773")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("309dcc16-8068-4155-8c07-d984e5f6d2c1")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _editInfo;
            RepoItemInfo _generalInfo;
            RepoItemInfo _keypassdemoInfo;
            RepoItemInfo _saveInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _helpInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "309dcc16-8068-4155-8c07-d984e5f6d2c1", "")
            {
                _editInfo = new RepoItemInfo(this, "Edit", "?/?/menuitem[@accessiblename='Edit']", 30000, null, "55bda606-67df-4872-bdfc-32df43f32521");
                _generalInfo = new RepoItemInfo(this, "General", "container[@controlname='m_splitHorizontal']//tree[@controlname='m_tvGroups']/?/?/treeitem[@accessiblename='NewDatabase']/treeitem[@accessiblename='General']", 30000, null, "731cd16e-225d-44ac-884d-806591befc43");
                _keypassdemoInfo = new RepoItemInfo(this, "KeyPassDemo", "container[@controlname='m_splitHorizontal']/?/?/container[@controlname='m_splitVertical']/?/?/table[@controlname='m_lvEntries']/?/?/cell[@columnindex='0']", 30000, null, "46da4645-7ef3-4ca6-ad16-bd55a2cdb5ef");
                _saveInfo = new RepoItemInfo(this, "Save", "?/?/button[@accessiblename='Save']", 30000, null, "492ff078-6995-4575-b015-9257f1dcfcf2");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "992f35e1-d7ac-4d7d-83f0-353d48259686");
                _helpInfo = new RepoItemInfo(this, "Help", "?/?/menuitem[@accessiblename='Help']", 30000, null, "feaf01d6-8bc0-4970-94f6-6b51d3cd44c4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("309dcc16-8068-4155-8c07-d984e5f6d2c1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("309dcc16-8068-4155-8c07-d984e5f6d2c1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("55bda606-67df-4872-bdfc-32df43f32521")]
            public virtual Ranorex.MenuItem Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("55bda606-67df-4872-bdfc-32df43f32521")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The General item.
            /// </summary>
            [RepositoryItem("731cd16e-225d-44ac-884d-806591befc43")]
            public virtual Ranorex.TreeItem General
            {
                get
                {
                    return _generalInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The General item info.
            /// </summary>
            [RepositoryItemInfo("731cd16e-225d-44ac-884d-806591befc43")]
            public virtual RepoItemInfo GeneralInfo
            {
                get
                {
                    return _generalInfo;
                }
            }

            /// <summary>
            /// The KeyPassDemo item.
            /// </summary>
            [RepositoryItem("46da4645-7ef3-4ca6-ad16-bd55a2cdb5ef")]
            public virtual Ranorex.Cell KeyPassDemo
            {
                get
                {
                    return _keypassdemoInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The KeyPassDemo item info.
            /// </summary>
            [RepositoryItemInfo("46da4645-7ef3-4ca6-ad16-bd55a2cdb5ef")]
            public virtual RepoItemInfo KeyPassDemoInfo
            {
                get
                {
                    return _keypassdemoInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("492ff078-6995-4575-b015-9257f1dcfcf2")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("492ff078-6995-4575-b015-9257f1dcfcf2")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("992f35e1-d7ac-4d7d-83f0-353d48259686")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("992f35e1-d7ac-4d7d-83f0-353d48259686")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Help item.
            /// </summary>
            [RepositoryItem("feaf01d6-8bc0-4970-94f6-6b51d3cd44c4")]
            public virtual Ranorex.MenuItem Help
            {
                get
                {
                    return _helpInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Help item info.
            /// </summary>
            [RepositoryItemInfo("feaf01d6-8bc0-4970-94f6-6b51d3cd44c4")]
            public virtual RepoItemInfo HelpInfo
            {
                get
                {
                    return _helpInfo;
                }
            }
        }

        /// <summary>
        /// The KeePassAppFolder folder.
        /// </summary>
        [RepositoryFolder("d2020d88-b02c-4afc-99bf-30a84cdcf093")]
        public partial class KeePassAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addentryInfo;
            RepoItemInfo _menuitem1yearInfo;
            RepoItemInfo _deleteentryInfo;
            RepoItemInfo _aboutkeepassInfo;

            /// <summary>
            /// Creates a new KeePass  folder.
            /// </summary>
            public KeePassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass", "/contextmenu[@processname='KeePass']", parentFolder, 30000, null, true, "d2020d88-b02c-4afc-99bf-30a84cdcf093", "")
            {
                _addentryInfo = new RepoItemInfo(this, "AddEntry", "menuitem[@accessiblename='Add Entry...']", 30000, null, "58f4ba93-99c4-4d5d-b88a-650097bd3b15");
                _menuitem1yearInfo = new RepoItemInfo(this, "MenuItem1Year", "menuitem[@accessiblename=$varExpires]", 30000, null, "1ac9803a-eaf3-426e-8b3c-e9a8339168c9");
                _deleteentryInfo = new RepoItemInfo(this, "DeleteEntry", "menuitem[@accessiblename='Delete Entry']", 30000, null, "d8f21a7b-d510-4594-a750-84aa6e9be3a6");
                _aboutkeepassInfo = new RepoItemInfo(this, "AboutKeePass", "menuitem[@accessiblename='About KeePass...']", 30000, null, "6bc9a2f6-501d-47de-9133-7164d695a093");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d2020d88-b02c-4afc-99bf-30a84cdcf093")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d2020d88-b02c-4afc-99bf-30a84cdcf093")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddEntry item.
            /// </summary>
            [RepositoryItem("58f4ba93-99c4-4d5d-b88a-650097bd3b15")]
            public virtual Ranorex.MenuItem AddEntry
            {
                get
                {
                    return _addentryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("58f4ba93-99c4-4d5d-b88a-650097bd3b15")]
            public virtual RepoItemInfo AddEntryInfo
            {
                get
                {
                    return _addentryInfo;
                }
            }

            /// <summary>
            /// The MenuItem1Year item.
            /// </summary>
            [RepositoryItem("1ac9803a-eaf3-426e-8b3c-e9a8339168c9")]
            public virtual Ranorex.MenuItem MenuItem1Year
            {
                get
                {
                    return _menuitem1yearInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItem1Year item info.
            /// </summary>
            [RepositoryItemInfo("1ac9803a-eaf3-426e-8b3c-e9a8339168c9")]
            public virtual RepoItemInfo MenuItem1YearInfo
            {
                get
                {
                    return _menuitem1yearInfo;
                }
            }

            /// <summary>
            /// The DeleteEntry item.
            /// </summary>
            [RepositoryItem("d8f21a7b-d510-4594-a750-84aa6e9be3a6")]
            public virtual Ranorex.MenuItem DeleteEntry
            {
                get
                {
                    return _deleteentryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The DeleteEntry item info.
            /// </summary>
            [RepositoryItemInfo("d8f21a7b-d510-4594-a750-84aa6e9be3a6")]
            public virtual RepoItemInfo DeleteEntryInfo
            {
                get
                {
                    return _deleteentryInfo;
                }
            }

            /// <summary>
            /// The AboutKeePass item.
            /// </summary>
            [RepositoryItem("6bc9a2f6-501d-47de-9133-7164d695a093")]
            public virtual Ranorex.MenuItem AboutKeePass
            {
                get
                {
                    return _aboutkeepassInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The AboutKeePass item info.
            /// </summary>
            [RepositoryItemInfo("6bc9a2f6-501d-47de-9133-7164d695a093")]
            public virtual RepoItemInfo AboutKeePassInfo
            {
                get
                {
                    return _aboutkeepassInfo;
                }
            }
        }

        /// <summary>
        /// The PwEntryFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("5044a4b7-ab54-4001-872e-7455f204cbca")]
        public partial class PwEntryFormAppFolder : RepoGenBaseFolder
        {
            MyFirstTestProjectRepositoryFolders.MTabEntry1Folder _mtabentry1;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new PwEntryForm  folder.
            /// </summary>
            public PwEntryFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PwEntryForm", "/form[@controlname='PwEntryForm']", parentFolder, 30000, null, true, "5044a4b7-ab54-4001-872e-7455f204cbca", "")
            {
                _mtabentry1 = new MyFirstTestProjectRepositoryFolders.MTabEntry1Folder(this);
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "3ad796b7-fd21-46d6-b973-b2c2d87e9957");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5044a4b7-ab54-4001-872e-7455f204cbca")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5044a4b7-ab54-4001-872e-7455f204cbca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("3ad796b7-fd21-46d6-b973-b2c2d87e9957")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("3ad796b7-fd21-46d6-b973-b2c2d87e9957")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }

            /// <summary>
            /// The MTabEntry1 folder.
            /// </summary>
            [RepositoryFolder("0a4475b3-5d21-49e8-882f-a788529af320")]
            public virtual MyFirstTestProjectRepositoryFolders.MTabEntry1Folder MTabEntry1
            {
                get { return _mtabentry1; }
            }
        }

        /// <summary>
        /// The MTabEntry1Folder folder.
        /// </summary>
        [RepositoryFolder("0a4475b3-5d21-49e8-882f-a788529af320")]
        public partial class MTabEntry1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _mtabentryInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _repeatInfo;
            RepoItemInfo _urlInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _mbtniconInfo;
            RepoItemInfo _mbtnstandardexpiresInfo;
            RepoItemInfo _textInfo;

            /// <summary>
            /// Creates a new MTabEntry1  folder.
            /// </summary>
            public MTabEntry1Folder(RepoGenBaseFolder parentFolder) :
                    base("MTabEntry1", "?/?/tabpage[@controlname='m_tabEntry']", parentFolder, 30000, null, false, "0a4475b3-5d21-49e8-882f-a788529af320", "")
            {
                _mtabentryInfo = new RepoItemInfo(this, "MTabEntry", "", 30000, null, "ad7e7325-bdc6-420d-9944-ed6393372f84");
                _passwordInfo = new RepoItemInfo(this, "Password", "?/?/text[@accessiblename='Password:']", 30000, null, "dbaf3614-3ee8-44d9-92a1-6cb2ed16a9d2");
                _repeatInfo = new RepoItemInfo(this, "Repeat", "?/?/text[@accessiblename='Repeat:']", 30000, null, "b6444985-fe2e-43bd-8280-8c0132122182");
                _urlInfo = new RepoItemInfo(this, "URL", "?/?/text[@accessiblename='URL:']", 30000, null, "98e4673e-0b70-4867-8d11-86b54fc80b35");
                _usernameInfo = new RepoItemInfo(this, "UserName", "?/?/text[@accessiblename='User name:']", 30000, null, "4d9a3231-19ee-4627-a7e6-cc0d0e885b45");
                _mbtniconInfo = new RepoItemInfo(this, "MBtnIcon", "button[@controlname='m_btnIcon']", 30000, null, "84385695-110c-4f7c-bcdf-533a98ea784f");
                _mbtnstandardexpiresInfo = new RepoItemInfo(this, "MBtnStandardExpires", "button[@controlname='m_btnStandardExpires']", 30000, null, "b6fc3a48-c940-4ffd-961c-4351b408620a");
                _textInfo = new RepoItemInfo(this, "Text", "text[@controlname='m_tbTitle']/text[@accessiblerole='Text']", 30000, null, "71966dcf-17ba-4050-a24e-044eb3f5b620");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0a4475b3-5d21-49e8-882f-a788529af320")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0a4475b3-5d21-49e8-882f-a788529af320")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MTabEntry item.
            /// </summary>
            [RepositoryItem("ad7e7325-bdc6-420d-9944-ed6393372f84")]
            public virtual Ranorex.TabPage MTabEntry
            {
                get
                {
                    return _mtabentryInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The MTabEntry item info.
            /// </summary>
            [RepositoryItemInfo("ad7e7325-bdc6-420d-9944-ed6393372f84")]
            public virtual RepoItemInfo MTabEntryInfo
            {
                get
                {
                    return _mtabentryInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("dbaf3614-3ee8-44d9-92a1-6cb2ed16a9d2")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("dbaf3614-3ee8-44d9-92a1-6cb2ed16a9d2")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Repeat item.
            /// </summary>
            [RepositoryItem("b6444985-fe2e-43bd-8280-8c0132122182")]
            public virtual Ranorex.Text Repeat
            {
                get
                {
                    return _repeatInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Repeat item info.
            /// </summary>
            [RepositoryItemInfo("b6444985-fe2e-43bd-8280-8c0132122182")]
            public virtual RepoItemInfo RepeatInfo
            {
                get
                {
                    return _repeatInfo;
                }
            }

            /// <summary>
            /// The URL item.
            /// </summary>
            [RepositoryItem("98e4673e-0b70-4867-8d11-86b54fc80b35")]
            public virtual Ranorex.Text URL
            {
                get
                {
                    return _urlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The URL item info.
            /// </summary>
            [RepositoryItemInfo("98e4673e-0b70-4867-8d11-86b54fc80b35")]
            public virtual RepoItemInfo URLInfo
            {
                get
                {
                    return _urlInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("4d9a3231-19ee-4627-a7e6-cc0d0e885b45")]
            public virtual Ranorex.Text UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("4d9a3231-19ee-4627-a7e6-cc0d0e885b45")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The MBtnIcon item.
            /// </summary>
            [RepositoryItem("84385695-110c-4f7c-bcdf-533a98ea784f")]
            public virtual Ranorex.Button MBtnIcon
            {
                get
                {
                    return _mbtniconInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnIcon item info.
            /// </summary>
            [RepositoryItemInfo("84385695-110c-4f7c-bcdf-533a98ea784f")]
            public virtual RepoItemInfo MBtnIconInfo
            {
                get
                {
                    return _mbtniconInfo;
                }
            }

            /// <summary>
            /// The MBtnStandardExpires item.
            /// </summary>
            [RepositoryItem("b6fc3a48-c940-4ffd-961c-4351b408620a")]
            public virtual Ranorex.Button MBtnStandardExpires
            {
                get
                {
                    return _mbtnstandardexpiresInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnStandardExpires item info.
            /// </summary>
            [RepositoryItemInfo("b6fc3a48-c940-4ffd-961c-4351b408620a")]
            public virtual RepoItemInfo MBtnStandardExpiresInfo
            {
                get
                {
                    return _mbtnstandardexpiresInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("71966dcf-17ba-4050-a24e-044eb3f5b620")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("71966dcf-17ba-4050-a24e-044eb3f5b620")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }
        }

        /// <summary>
        /// The IconPickerFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("e377384c-8354-487b-bc18-b529a5181c52")]
        public partial class IconPickerFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _listitem1Info;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new IconPickerForm  folder.
            /// </summary>
            public IconPickerFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IconPickerForm", "/form[@controlname='IconPickerForm']", parentFolder, 30000, null, true, "e377384c-8354-487b-bc18-b529a5181c52", "")
            {
                _listitem1Info = new RepoItemInfo(this, "ListItem1", "list[@controlname='m_lvIcons']/listitem[@text='1']", 30000, null, "bedb2758-e6a9-4bb1-9d7f-75945300a9d1");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "7fdbc5f3-9b9f-4f51-bdee-c17451abb382");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e377384c-8354-487b-bc18-b529a5181c52")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e377384c-8354-487b-bc18-b529a5181c52")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ListItem1 item.
            /// </summary>
            [RepositoryItem("bedb2758-e6a9-4bb1-9d7f-75945300a9d1")]
            public virtual Ranorex.ListItem ListItem1
            {
                get
                {
                    return _listitem1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem1 item info.
            /// </summary>
            [RepositoryItemInfo("bedb2758-e6a9-4bb1-9d7f-75945300a9d1")]
            public virtual RepoItemInfo ListItem1Info
            {
                get
                {
                    return _listitem1Info;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("7fdbc5f3-9b9f-4f51-bdee-c17451abb382")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("7fdbc5f3-9b9f-4f51-bdee-c17451abb382")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }
        }

        /// <summary>
        /// The KeePass1AppFolder folder.
        /// </summary>
        [RepositoryFolder("eea33797-6951-4fbb-b21e-a86359bb687d")]
        public partial class KeePass1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _buttonsaveInfo;
            RepoItemInfo _buttondiscardchangesInfo;

            /// <summary>
            /// Creates a new KeePass1  folder.
            /// </summary>
            public KeePass1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass1", "/form[@title='KeePass' and @processname='KeePass']", parentFolder, 30000, null, true, "eea33797-6951-4fbb-b21e-a86359bb687d", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "a541d56b-2ed0-429c-8d91-eb6bb8dac9ff");
                _buttonsaveInfo = new RepoItemInfo(this, "ButtonSave", "?/?/element[@instance='0']/button[@text='&Save']", 30000, null, "4f60538b-62d7-4dce-a957-d3b1b5c27198");
                _buttondiscardchangesInfo = new RepoItemInfo(this, "ButtonDiscardChanges", "?/?/element[@instance='1']/button[@text='&Discard changes']", 30000, null, "040694ae-a863-428c-b14f-641d2354b4c8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eea33797-6951-4fbb-b21e-a86359bb687d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eea33797-6951-4fbb-b21e-a86359bb687d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("a541d56b-2ed0-429c-8d91-eb6bb8dac9ff")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("a541d56b-2ed0-429c-8d91-eb6bb8dac9ff")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The ButtonSave item.
            /// </summary>
            [RepositoryItem("4f60538b-62d7-4dce-a957-d3b1b5c27198")]
            public virtual Ranorex.Button ButtonSave
            {
                get
                {
                    return _buttonsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSave item info.
            /// </summary>
            [RepositoryItemInfo("4f60538b-62d7-4dce-a957-d3b1b5c27198")]
            public virtual RepoItemInfo ButtonSaveInfo
            {
                get
                {
                    return _buttonsaveInfo;
                }
            }

            /// <summary>
            /// The ButtonDiscardChanges item.
            /// </summary>
            [RepositoryItem("040694ae-a863-428c-b14f-641d2354b4c8")]
            public virtual Ranorex.Button ButtonDiscardChanges
            {
                get
                {
                    return _buttondiscardchangesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonDiscardChanges item info.
            /// </summary>
            [RepositoryItemInfo("040694ae-a863-428c-b14f-641d2354b4c8")]
            public virtual RepoItemInfo ButtonDiscardChangesInfo
            {
                get
                {
                    return _buttondiscardchangesInfo;
                }
            }
        }

        /// <summary>
        /// The AboutFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("e46e2838-cbaa-4645-93f7-8581db15098c")]
        public partial class AboutFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cell2201Info;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new AboutForm  folder.
            /// </summary>
            public AboutFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AboutForm", "/form[@controlname='AboutForm']", parentFolder, 30000, null, true, "e46e2838-cbaa-4645-93f7-8581db15098c", "")
            {
                _cell2201Info = new RepoItemInfo(this, "Cell2201", "table[@controlname='m_lvComponents']/?/?/cell[@columnindex='1' and @rowindex='1']", 30000, null, "c900914b-ced7-46c4-ad6a-94c58f3a49d3");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "a98460c1-1bfb-4678-b4c5-64214b4ebb01");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e46e2838-cbaa-4645-93f7-8581db15098c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e46e2838-cbaa-4645-93f7-8581db15098c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cell2201 item.
            /// </summary>
            [RepositoryItem("c900914b-ced7-46c4-ad6a-94c58f3a49d3")]
            public virtual Ranorex.Cell Cell2201
            {
                get
                {
                    return _cell2201Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell2201 item info.
            /// </summary>
            [RepositoryItemInfo("c900914b-ced7-46c4-ad6a-94c58f3a49d3")]
            public virtual RepoItemInfo Cell2201Info
            {
                get
                {
                    return _cell2201Info;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("a98460c1-1bfb-4678-b4c5-64214b4ebb01")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("a98460c1-1bfb-4678-b4c5-64214b4ebb01")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}