///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyFirstTestProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyFirstTestProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("f7bc0049-88e2-4852-88d2-fcf38eb3b04b")]
    public partial class MyFirstTestProjectRepository : RepoGenBaseFolder
    {
        static MyFirstTestProjectRepository instance = new MyFirstTestProjectRepository();
        MyFirstTestProjectRepositoryFolders.LoginPageAppFolder _loginpage;
        MyFirstTestProjectRepositoryFolders.MainFormAppFolder _mainform;
        MyFirstTestProjectRepositoryFolders.KeePassAppFolder _keepass;
        MyFirstTestProjectRepositoryFolders.PwEntryFormAppFolder _pwentryform;
        MyFirstTestProjectRepositoryFolders.IconPickerFormAppFolder _iconpickerform;
        MyFirstTestProjectRepositoryFolders.KeePass1AppFolder _keepass1;
        MyFirstTestProjectRepositoryFolders.AboutFormAppFolder _aboutform;

        /// <summary>
        /// Gets the singleton class instance representing the MyFirstTestProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("f7bc0049-88e2-4852-88d2-fcf38eb3b04b")]
        public static MyFirstTestProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyFirstTestProjectRepository() 
            : base("MyFirstTestProjectRepository", "/", null, 0, false, "f7bc0049-88e2-4852-88d2-fcf38eb3b04b", ".\\RepositoryImages\\MyFirstTestProjectRepositoryf7bc0049.rximgres")
        {
            _loginpage = new MyFirstTestProjectRepositoryFolders.LoginPageAppFolder(this);
            _mainform = new MyFirstTestProjectRepositoryFolders.MainFormAppFolder(this);
            _keepass = new MyFirstTestProjectRepositoryFolders.KeePassAppFolder(this);
            _pwentryform = new MyFirstTestProjectRepositoryFolders.PwEntryFormAppFolder(this);
            _iconpickerform = new MyFirstTestProjectRepositoryFolders.IconPickerFormAppFolder(this);
            _keepass1 = new MyFirstTestProjectRepositoryFolders.KeePass1AppFolder(this);
            _aboutform = new MyFirstTestProjectRepositoryFolders.AboutFormAppFolder(this);
        }

#region Variables

        string _varExpires = "1 Year";

        /// <summary>
        /// Gets or sets the value of variable varExpires.
        /// </summary>
        [TestVariable("c57b4175-cd8f-4f08-999d-4a396515ce22")]
        public string varExpires
        {
            get { return _varExpires; }
            set { _varExpires = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f7bc0049-88e2-4852-88d2-fcf38eb3b04b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LoginPage folder.
        /// </summary>
        [RepositoryFolder("85ca4e89-8c5b-4025-9966-63a3db391f98")]
        public virtual MyFirstTestProjectRepositoryFolders.LoginPageAppFolder LoginPage
        {
            get { return _loginpage; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("309dcc16-8068-4155-8c07-d984e5f6d2c1")]
        public virtual MyFirstTestProjectRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The KeePass folder.
        /// </summary>
        [RepositoryFolder("d2020d88-b02c-4afc-99bf-30a84cdcf093")]
        public virtual MyFirstTestProjectRepositoryFolders.KeePassAppFolder KeePass
        {
            get { return _keepass; }
        }

        /// <summary>
        /// The PwEntryForm folder.
        /// </summary>
        [RepositoryFolder("5044a4b7-ab54-4001-872e-7455f204cbca")]
        public virtual MyFirstTestProjectRepositoryFolders.PwEntryFormAppFolder PwEntryForm
        {
            get { return _pwentryform; }
        }

        /// <summary>
        /// The IconPickerForm folder.
        /// </summary>
        [RepositoryFolder("e377384c-8354-487b-bc18-b529a5181c52")]
        public virtual MyFirstTestProjectRepositoryFolders.IconPickerFormAppFolder IconPickerForm
        {
            get { return _iconpickerform; }
        }

        /// <summary>
        /// The KeePass1 folder.
        /// </summary>
        [RepositoryFolder("eea33797-6951-4fbb-b21e-a86359bb687d")]
        public virtual MyFirstTestProjectRepositoryFolders.KeePass1AppFolder KeePass1
        {
            get { return _keepass1; }
        }

        /// <summary>
        /// The AboutForm folder.
        /// </summary>
        [RepositoryFolder("e46e2838-cbaa-4645-93f7-8581db15098c")]
        public virtual MyFirstTestProjectRepositoryFolders.AboutFormAppFolder AboutForm
        {
            get { return _aboutform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class MyFirstTestProjectRepositoryFolders
    {
        /// <summary>
        /// The LoginPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("85ca4e89-8c5b-4025-9966-63a3db391f98")]
        public partial class LoginPageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txt_masterpasswordInfo;
            RepoItemInfo _btn_masterokInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, true, "85ca4e89-8c5b-4025-9966-63a3db391f98", "")
            {
                _txt_masterpasswordInfo = new RepoItemInfo(this, "txt_MasterPassword", "?/?/text[@accessiblerole='Text']", 30000, null, "93235cea-fc03-4f17-ab9e-e68a0fc05916");
                _btn_masterokInfo = new RepoItemInfo(this, "btn_MasterOk", "button[@controlname='m_btnOK']", 30000, null, "98625ce7-fc63-405a-917c-0ec3aa539773");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("85ca4e89-8c5b-4025-9966-63a3db391f98")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("85ca4e89-8c5b-4025-9966-63a3db391f98")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txt_MasterPassword item.
            /// </summary>
            [RepositoryItem("93235cea-fc03-4f17-ab9e-e68a0fc05916")]
            public virtual Ranorex.Text txt_MasterPassword
            {
                get
                {
                    return _txt_masterpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txt_MasterPassword item info.
            /// </summary>
            [RepositoryItemInfo("93235cea-fc03-4f17-ab9e-e68a0fc05916")]
            public virtual RepoItemInfo txt_MasterPasswordInfo
            {
                get
                {
                    return _txt_masterpasswordInfo;
                }
            }

            /// <summary>
            /// The btn_MasterOk item.
            /// </summary>
            [RepositoryItem("98625ce7-fc63-405a-917c-0ec3aa539773")]
            public virtual Ranorex.Button btn_MasterOk
            {
                get
                {
                    return _btn_masterokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_MasterOk item info.
            /// </summary>
            [RepositoryItemInfo("98625ce7-fc63-405a-917c-0ec3aa539773")]
            public virtual RepoItemInfo btn_MasterOkInfo
            {
                get
                {
                    return _btn_masterokInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("309dcc16-8068-4155-8c07-d984e5f6d2c1")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuitem_editInfo;
            RepoItemInfo _lable_keypassdemoInfo;
            RepoItemInfo _btn_saveInfo;
            RepoItemInfo _btn_closeInfo;
            RepoItemInfo _menuitem_helpInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "309dcc16-8068-4155-8c07-d984e5f6d2c1", "")
            {
                _menuitem_editInfo = new RepoItemInfo(this, "menuItem_Edit", "?/?/menuitem[@accessiblename='Edit']", 30000, null, "55bda606-67df-4872-bdfc-32df43f32521");
                _lable_keypassdemoInfo = new RepoItemInfo(this, "lable_KeyPassDemo", "container[@controlname='m_splitHorizontal']/?/?/container[@controlname='m_splitVertical']/?/?/table[@controlname='m_lvEntries']/?/?/cell[@columnindex='0']", 30000, null, "46da4645-7ef3-4ca6-ad16-bd55a2cdb5ef");
                _btn_saveInfo = new RepoItemInfo(this, "btn_Save", "?/?/button[@accessiblename='Save']", 30000, null, "492ff078-6995-4575-b015-9257f1dcfcf2");
                _btn_closeInfo = new RepoItemInfo(this, "btn_Close", "?/?/button[@accessiblename='Close']", 30000, null, "992f35e1-d7ac-4d7d-83f0-353d48259686");
                _menuitem_helpInfo = new RepoItemInfo(this, "menuItem_Help", "?/?/menuitem[@accessiblename='Help']", 30000, null, "feaf01d6-8bc0-4970-94f6-6b51d3cd44c4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("309dcc16-8068-4155-8c07-d984e5f6d2c1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("309dcc16-8068-4155-8c07-d984e5f6d2c1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The menuItem_Edit item.
            /// </summary>
            [RepositoryItem("55bda606-67df-4872-bdfc-32df43f32521")]
            public virtual Ranorex.MenuItem menuItem_Edit
            {
                get
                {
                    return _menuitem_editInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The menuItem_Edit item info.
            /// </summary>
            [RepositoryItemInfo("55bda606-67df-4872-bdfc-32df43f32521")]
            public virtual RepoItemInfo menuItem_EditInfo
            {
                get
                {
                    return _menuitem_editInfo;
                }
            }

            /// <summary>
            /// The lable_KeyPassDemo item.
            /// </summary>
            [RepositoryItem("46da4645-7ef3-4ca6-ad16-bd55a2cdb5ef")]
            public virtual Ranorex.Cell lable_KeyPassDemo
            {
                get
                {
                    return _lable_keypassdemoInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The lable_KeyPassDemo item info.
            /// </summary>
            [RepositoryItemInfo("46da4645-7ef3-4ca6-ad16-bd55a2cdb5ef")]
            public virtual RepoItemInfo lable_KeyPassDemoInfo
            {
                get
                {
                    return _lable_keypassdemoInfo;
                }
            }

            /// <summary>
            /// The btn_Save item.
            /// </summary>
            [RepositoryItem("492ff078-6995-4575-b015-9257f1dcfcf2")]
            public virtual Ranorex.Button btn_Save
            {
                get
                {
                    return _btn_saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_Save item info.
            /// </summary>
            [RepositoryItemInfo("492ff078-6995-4575-b015-9257f1dcfcf2")]
            public virtual RepoItemInfo btn_SaveInfo
            {
                get
                {
                    return _btn_saveInfo;
                }
            }

            /// <summary>
            /// The btn_Close item.
            /// </summary>
            [RepositoryItem("992f35e1-d7ac-4d7d-83f0-353d48259686")]
            public virtual Ranorex.Button btn_Close
            {
                get
                {
                    return _btn_closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_Close item info.
            /// </summary>
            [RepositoryItemInfo("992f35e1-d7ac-4d7d-83f0-353d48259686")]
            public virtual RepoItemInfo btn_CloseInfo
            {
                get
                {
                    return _btn_closeInfo;
                }
            }

            /// <summary>
            /// The menuItem_Help item.
            /// </summary>
            [RepositoryItem("feaf01d6-8bc0-4970-94f6-6b51d3cd44c4")]
            public virtual Ranorex.MenuItem menuItem_Help
            {
                get
                {
                    return _menuitem_helpInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The menuItem_Help item info.
            /// </summary>
            [RepositoryItemInfo("feaf01d6-8bc0-4970-94f6-6b51d3cd44c4")]
            public virtual RepoItemInfo menuItem_HelpInfo
            {
                get
                {
                    return _menuitem_helpInfo;
                }
            }
        }

        /// <summary>
        /// The KeePassAppFolder folder.
        /// </summary>
        [RepositoryFolder("d2020d88-b02c-4afc-99bf-30a84cdcf093")]
        public partial class KeePassAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuitem_addentryInfo;
            RepoItemInfo _menuitem_1yearInfo;
            RepoItemInfo _menuitem_deleteentryInfo;
            RepoItemInfo _menuitem_aboutkeepassInfo;

            /// <summary>
            /// Creates a new KeePass  folder.
            /// </summary>
            public KeePassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass", "/contextmenu[@processname='KeePass']", parentFolder, 30000, null, true, "d2020d88-b02c-4afc-99bf-30a84cdcf093", "")
            {
                _menuitem_addentryInfo = new RepoItemInfo(this, "menuItem_AddEntry", "menuitem[@accessiblename='Add Entry...']", 30000, null, "58f4ba93-99c4-4d5d-b88a-650097bd3b15");
                _menuitem_1yearInfo = new RepoItemInfo(this, "menuItem_1Year", "menuitem[@accessiblename=$varExpires]", 30000, null, "1ac9803a-eaf3-426e-8b3c-e9a8339168c9");
                _menuitem_deleteentryInfo = new RepoItemInfo(this, "menuItem_DeleteEntry", "menuitem[@accessiblename='Delete Entry']", 30000, null, "d8f21a7b-d510-4594-a750-84aa6e9be3a6");
                _menuitem_aboutkeepassInfo = new RepoItemInfo(this, "menuItem_AboutKeePass", "menuitem[@accessiblename='About KeePass...']", 30000, null, "6bc9a2f6-501d-47de-9133-7164d695a093");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d2020d88-b02c-4afc-99bf-30a84cdcf093")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d2020d88-b02c-4afc-99bf-30a84cdcf093")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The menuItem_AddEntry item.
            /// </summary>
            [RepositoryItem("58f4ba93-99c4-4d5d-b88a-650097bd3b15")]
            public virtual Ranorex.MenuItem menuItem_AddEntry
            {
                get
                {
                    return _menuitem_addentryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The menuItem_AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("58f4ba93-99c4-4d5d-b88a-650097bd3b15")]
            public virtual RepoItemInfo menuItem_AddEntryInfo
            {
                get
                {
                    return _menuitem_addentryInfo;
                }
            }

            /// <summary>
            /// The menuItem_1Year item.
            /// </summary>
            [RepositoryItem("1ac9803a-eaf3-426e-8b3c-e9a8339168c9")]
            public virtual Ranorex.MenuItem menuItem_1Year
            {
                get
                {
                    return _menuitem_1yearInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The menuItem_1Year item info.
            /// </summary>
            [RepositoryItemInfo("1ac9803a-eaf3-426e-8b3c-e9a8339168c9")]
            public virtual RepoItemInfo menuItem_1YearInfo
            {
                get
                {
                    return _menuitem_1yearInfo;
                }
            }

            /// <summary>
            /// The menuItem_DeleteEntry item.
            /// </summary>
            [RepositoryItem("d8f21a7b-d510-4594-a750-84aa6e9be3a6")]
            public virtual Ranorex.MenuItem menuItem_DeleteEntry
            {
                get
                {
                    return _menuitem_deleteentryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The menuItem_DeleteEntry item info.
            /// </summary>
            [RepositoryItemInfo("d8f21a7b-d510-4594-a750-84aa6e9be3a6")]
            public virtual RepoItemInfo menuItem_DeleteEntryInfo
            {
                get
                {
                    return _menuitem_deleteentryInfo;
                }
            }

            /// <summary>
            /// The menuItem_AboutKeePass item.
            /// </summary>
            [RepositoryItem("6bc9a2f6-501d-47de-9133-7164d695a093")]
            public virtual Ranorex.MenuItem menuItem_AboutKeePass
            {
                get
                {
                    return _menuitem_aboutkeepassInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The menuItem_AboutKeePass item info.
            /// </summary>
            [RepositoryItemInfo("6bc9a2f6-501d-47de-9133-7164d695a093")]
            public virtual RepoItemInfo menuItem_AboutKeePassInfo
            {
                get
                {
                    return _menuitem_aboutkeepassInfo;
                }
            }
        }

        /// <summary>
        /// The PwEntryFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("5044a4b7-ab54-4001-872e-7455f204cbca")]
        public partial class PwEntryFormAppFolder : RepoGenBaseFolder
        {
            MyFirstTestProjectRepositoryFolders.MTabEntry1Folder _mtabentry1;
            RepoItemInfo _btn_okInfo;

            /// <summary>
            /// Creates a new PwEntryForm  folder.
            /// </summary>
            public PwEntryFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PwEntryForm", "/form[@controlname='PwEntryForm']", parentFolder, 30000, null, true, "5044a4b7-ab54-4001-872e-7455f204cbca", "")
            {
                _mtabentry1 = new MyFirstTestProjectRepositoryFolders.MTabEntry1Folder(this);
                _btn_okInfo = new RepoItemInfo(this, "btn_OK", "button[@controlname='m_btnOK']", 30000, null, "3ad796b7-fd21-46d6-b973-b2c2d87e9957");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5044a4b7-ab54-4001-872e-7455f204cbca")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5044a4b7-ab54-4001-872e-7455f204cbca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btn_OK item.
            /// </summary>
            [RepositoryItem("3ad796b7-fd21-46d6-b973-b2c2d87e9957")]
            public virtual Ranorex.Button btn_OK
            {
                get
                {
                    return _btn_okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_OK item info.
            /// </summary>
            [RepositoryItemInfo("3ad796b7-fd21-46d6-b973-b2c2d87e9957")]
            public virtual RepoItemInfo btn_OKInfo
            {
                get
                {
                    return _btn_okInfo;
                }
            }

            /// <summary>
            /// The MTabEntry1 folder.
            /// </summary>
            [RepositoryFolder("0a4475b3-5d21-49e8-882f-a788529af320")]
            public virtual MyFirstTestProjectRepositoryFolders.MTabEntry1Folder MTabEntry1
            {
                get { return _mtabentry1; }
            }
        }

        /// <summary>
        /// The MTabEntry1Folder folder.
        /// </summary>
        [RepositoryFolder("0a4475b3-5d21-49e8-882f-a788529af320")]
        public partial class MTabEntry1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _txt_passwordInfo;
            RepoItemInfo _txt_repeatInfo;
            RepoItemInfo _txt_urlInfo;
            RepoItemInfo _txt_usernameInfo;
            RepoItemInfo _btn_iconInfo;
            RepoItemInfo _btn_exeptionInfo;
            RepoItemInfo _txt_titleInfo;

            /// <summary>
            /// Creates a new MTabEntry1  folder.
            /// </summary>
            public MTabEntry1Folder(RepoGenBaseFolder parentFolder) :
                    base("MTabEntry1", "?/?/tabpage[@controlname='m_tabEntry']", parentFolder, 30000, null, false, "0a4475b3-5d21-49e8-882f-a788529af320", "")
            {
                _txt_passwordInfo = new RepoItemInfo(this, "txt_Password", "?/?/text[@accessiblename='Password:']", 30000, null, "dbaf3614-3ee8-44d9-92a1-6cb2ed16a9d2");
                _txt_repeatInfo = new RepoItemInfo(this, "txt_Repeat", "?/?/text[@accessiblename='Repeat:']", 30000, null, "b6444985-fe2e-43bd-8280-8c0132122182");
                _txt_urlInfo = new RepoItemInfo(this, "txt_URL", "?/?/text[@accessiblename='URL:']", 30000, null, "98e4673e-0b70-4867-8d11-86b54fc80b35");
                _txt_usernameInfo = new RepoItemInfo(this, "txt_UserName", "?/?/text[@accessiblename='User name:']", 30000, null, "4d9a3231-19ee-4627-a7e6-cc0d0e885b45");
                _btn_iconInfo = new RepoItemInfo(this, "btn_Icon", "button[@controlname='m_btnIcon']", 30000, null, "84385695-110c-4f7c-bcdf-533a98ea784f");
                _btn_exeptionInfo = new RepoItemInfo(this, "btn_Exeption", "button[@controlname='m_btnStandardExpires']", 30000, null, "b6fc3a48-c940-4ffd-961c-4351b408620a");
                _txt_titleInfo = new RepoItemInfo(this, "txt_Title", "text[@controlname='m_tbTitle']/text[@accessiblerole='Text']", 30000, null, "71966dcf-17ba-4050-a24e-044eb3f5b620");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0a4475b3-5d21-49e8-882f-a788529af320")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0a4475b3-5d21-49e8-882f-a788529af320")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txt_Password item.
            /// </summary>
            [RepositoryItem("dbaf3614-3ee8-44d9-92a1-6cb2ed16a9d2")]
            public virtual Ranorex.Text txt_Password
            {
                get
                {
                    return _txt_passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txt_Password item info.
            /// </summary>
            [RepositoryItemInfo("dbaf3614-3ee8-44d9-92a1-6cb2ed16a9d2")]
            public virtual RepoItemInfo txt_PasswordInfo
            {
                get
                {
                    return _txt_passwordInfo;
                }
            }

            /// <summary>
            /// The txt_Repeat item.
            /// </summary>
            [RepositoryItem("b6444985-fe2e-43bd-8280-8c0132122182")]
            public virtual Ranorex.Text txt_Repeat
            {
                get
                {
                    return _txt_repeatInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txt_Repeat item info.
            /// </summary>
            [RepositoryItemInfo("b6444985-fe2e-43bd-8280-8c0132122182")]
            public virtual RepoItemInfo txt_RepeatInfo
            {
                get
                {
                    return _txt_repeatInfo;
                }
            }

            /// <summary>
            /// The txt_URL item.
            /// </summary>
            [RepositoryItem("98e4673e-0b70-4867-8d11-86b54fc80b35")]
            public virtual Ranorex.Text txt_URL
            {
                get
                {
                    return _txt_urlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txt_URL item info.
            /// </summary>
            [RepositoryItemInfo("98e4673e-0b70-4867-8d11-86b54fc80b35")]
            public virtual RepoItemInfo txt_URLInfo
            {
                get
                {
                    return _txt_urlInfo;
                }
            }

            /// <summary>
            /// The txt_UserName item.
            /// </summary>
            [RepositoryItem("4d9a3231-19ee-4627-a7e6-cc0d0e885b45")]
            public virtual Ranorex.Text txt_UserName
            {
                get
                {
                    return _txt_usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txt_UserName item info.
            /// </summary>
            [RepositoryItemInfo("4d9a3231-19ee-4627-a7e6-cc0d0e885b45")]
            public virtual RepoItemInfo txt_UserNameInfo
            {
                get
                {
                    return _txt_usernameInfo;
                }
            }

            /// <summary>
            /// The btn_Icon item.
            /// </summary>
            [RepositoryItem("84385695-110c-4f7c-bcdf-533a98ea784f")]
            public virtual Ranorex.Button btn_Icon
            {
                get
                {
                    return _btn_iconInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_Icon item info.
            /// </summary>
            [RepositoryItemInfo("84385695-110c-4f7c-bcdf-533a98ea784f")]
            public virtual RepoItemInfo btn_IconInfo
            {
                get
                {
                    return _btn_iconInfo;
                }
            }

            /// <summary>
            /// The btn_Exeption item.
            /// </summary>
            [RepositoryItem("b6fc3a48-c940-4ffd-961c-4351b408620a")]
            public virtual Ranorex.Button btn_Exeption
            {
                get
                {
                    return _btn_exeptionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_Exeption item info.
            /// </summary>
            [RepositoryItemInfo("b6fc3a48-c940-4ffd-961c-4351b408620a")]
            public virtual RepoItemInfo btn_ExeptionInfo
            {
                get
                {
                    return _btn_exeptionInfo;
                }
            }

            /// <summary>
            /// The txt_Title item.
            /// </summary>
            [RepositoryItem("71966dcf-17ba-4050-a24e-044eb3f5b620")]
            public virtual Ranorex.Text txt_Title
            {
                get
                {
                    return _txt_titleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txt_Title item info.
            /// </summary>
            [RepositoryItemInfo("71966dcf-17ba-4050-a24e-044eb3f5b620")]
            public virtual RepoItemInfo txt_TitleInfo
            {
                get
                {
                    return _txt_titleInfo;
                }
            }
        }

        /// <summary>
        /// The IconPickerFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("e377384c-8354-487b-bc18-b529a5181c52")]
        public partial class IconPickerFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _listitem1Info;
            RepoItemInfo _btn_closeInfo;

            /// <summary>
            /// Creates a new IconPickerForm  folder.
            /// </summary>
            public IconPickerFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IconPickerForm", "/form[@controlname='IconPickerForm']", parentFolder, 30000, null, true, "e377384c-8354-487b-bc18-b529a5181c52", "")
            {
                _listitem1Info = new RepoItemInfo(this, "ListItem1", "list[@controlname='m_lvIcons']/listitem[@text='1']", 30000, null, "bedb2758-e6a9-4bb1-9d7f-75945300a9d1");
                _btn_closeInfo = new RepoItemInfo(this, "btn_Close", "button[@controlname='m_btnOK']", 30000, null, "7fdbc5f3-9b9f-4f51-bdee-c17451abb382");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e377384c-8354-487b-bc18-b529a5181c52")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e377384c-8354-487b-bc18-b529a5181c52")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ListItem1 item.
            /// </summary>
            [RepositoryItem("bedb2758-e6a9-4bb1-9d7f-75945300a9d1")]
            public virtual Ranorex.ListItem ListItem1
            {
                get
                {
                    return _listitem1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem1 item info.
            /// </summary>
            [RepositoryItemInfo("bedb2758-e6a9-4bb1-9d7f-75945300a9d1")]
            public virtual RepoItemInfo ListItem1Info
            {
                get
                {
                    return _listitem1Info;
                }
            }

            /// <summary>
            /// The btn_Close item.
            /// </summary>
            [RepositoryItem("7fdbc5f3-9b9f-4f51-bdee-c17451abb382")]
            public virtual Ranorex.Button btn_Close
            {
                get
                {
                    return _btn_closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_Close item info.
            /// </summary>
            [RepositoryItemInfo("7fdbc5f3-9b9f-4f51-bdee-c17451abb382")]
            public virtual RepoItemInfo btn_CloseInfo
            {
                get
                {
                    return _btn_closeInfo;
                }
            }
        }

        /// <summary>
        /// The KeePass1AppFolder folder.
        /// </summary>
        [RepositoryFolder("eea33797-6951-4fbb-b21e-a86359bb687d")]
        public partial class KeePass1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn_okInfo;
            RepoItemInfo _btn_saveInfo;
            RepoItemInfo _btn_discardchangesInfo;

            /// <summary>
            /// Creates a new KeePass1  folder.
            /// </summary>
            public KeePass1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass1", "/form[@title='KeePass' and @processname='KeePass']", parentFolder, 30000, null, true, "eea33797-6951-4fbb-b21e-a86359bb687d", "")
            {
                _btn_okInfo = new RepoItemInfo(this, "btn_Ok", "button[@text='OK']", 30000, null, "a541d56b-2ed0-429c-8d91-eb6bb8dac9ff");
                _btn_saveInfo = new RepoItemInfo(this, "btn_Save", "?/?/element[@instance='0']/button[@text='&Save']", 30000, null, "4f60538b-62d7-4dce-a957-d3b1b5c27198");
                _btn_discardchangesInfo = new RepoItemInfo(this, "btn_DiscardChanges", "?/?/element[@instance='1']/button[@text='&Discard changes']", 30000, null, "040694ae-a863-428c-b14f-641d2354b4c8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("eea33797-6951-4fbb-b21e-a86359bb687d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("eea33797-6951-4fbb-b21e-a86359bb687d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btn_Ok item.
            /// </summary>
            [RepositoryItem("a541d56b-2ed0-429c-8d91-eb6bb8dac9ff")]
            public virtual Ranorex.Button btn_Ok
            {
                get
                {
                    return _btn_okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_Ok item info.
            /// </summary>
            [RepositoryItemInfo("a541d56b-2ed0-429c-8d91-eb6bb8dac9ff")]
            public virtual RepoItemInfo btn_OkInfo
            {
                get
                {
                    return _btn_okInfo;
                }
            }

            /// <summary>
            /// The btn_Save item.
            /// </summary>
            [RepositoryItem("4f60538b-62d7-4dce-a957-d3b1b5c27198")]
            public virtual Ranorex.Button btn_Save
            {
                get
                {
                    return _btn_saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_Save item info.
            /// </summary>
            [RepositoryItemInfo("4f60538b-62d7-4dce-a957-d3b1b5c27198")]
            public virtual RepoItemInfo btn_SaveInfo
            {
                get
                {
                    return _btn_saveInfo;
                }
            }

            /// <summary>
            /// The btn_DiscardChanges item.
            /// </summary>
            [RepositoryItem("040694ae-a863-428c-b14f-641d2354b4c8")]
            public virtual Ranorex.Button btn_DiscardChanges
            {
                get
                {
                    return _btn_discardchangesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_DiscardChanges item info.
            /// </summary>
            [RepositoryItemInfo("040694ae-a863-428c-b14f-641d2354b4c8")]
            public virtual RepoItemInfo btn_DiscardChangesInfo
            {
                get
                {
                    return _btn_discardchangesInfo;
                }
            }
        }

        /// <summary>
        /// The AboutFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("e46e2838-cbaa-4645-93f7-8581db15098c")]
        public partial class AboutFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cell_versionInfo;
            RepoItemInfo _btn_okInfo;

            /// <summary>
            /// Creates a new AboutForm  folder.
            /// </summary>
            public AboutFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AboutForm", "/form[@controlname='AboutForm']", parentFolder, 30000, null, true, "e46e2838-cbaa-4645-93f7-8581db15098c", "")
            {
                _cell_versionInfo = new RepoItemInfo(this, "Cell_Version", "table[@controlname='m_lvComponents']/?/?/cell[@columnindex='1' and @rowindex='1']", 30000, null, "c900914b-ced7-46c4-ad6a-94c58f3a49d3");
                _btn_okInfo = new RepoItemInfo(this, "btn_Ok", "button[@controlname='m_btnOK']", 30000, null, "a98460c1-1bfb-4678-b4c5-64214b4ebb01");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e46e2838-cbaa-4645-93f7-8581db15098c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e46e2838-cbaa-4645-93f7-8581db15098c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cell_Version item.
            /// </summary>
            [RepositoryItem("c900914b-ced7-46c4-ad6a-94c58f3a49d3")]
            public virtual Ranorex.Cell Cell_Version
            {
                get
                {
                    return _cell_versionInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell_Version item info.
            /// </summary>
            [RepositoryItemInfo("c900914b-ced7-46c4-ad6a-94c58f3a49d3")]
            public virtual RepoItemInfo Cell_VersionInfo
            {
                get
                {
                    return _cell_versionInfo;
                }
            }

            /// <summary>
            /// The btn_Ok item.
            /// </summary>
            [RepositoryItem("a98460c1-1bfb-4678-b4c5-64214b4ebb01")]
            public virtual Ranorex.Button btn_Ok
            {
                get
                {
                    return _btn_okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_Ok item info.
            /// </summary>
            [RepositoryItemInfo("a98460c1-1bfb-4678-b4c5-64214b4ebb01")]
            public virtual RepoItemInfo btn_OkInfo
            {
                get
                {
                    return _btn_okInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}